// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gms.data;

#nullable disable

namespace gms.data.Migrations.Entities
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240316232850_UpdateGymBranchEntityToHaveRelation")]
    partial class UpdateGymBranchEntityToHaveRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gms.data.Models.Gym.GymBranchEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainBranch")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("gms.GymBranch", (string)null);
                });

            modelBuilder.Entity("gms.data.Models.Gym.GymEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("gms.Gym", (string)null);
                });

            modelBuilder.Entity("gms.data.Models.Shared.CountryEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Flag")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("gms.Country", (string)null);
                });

            modelBuilder.Entity("gms.data.Models.Subscription.PaymentMethodEnumEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("gms.PaymentMethodEnum", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 16, 23, 28, 48, 761, DateTimeKind.Utc).AddTicks(1666),
                            IsDeleted = false,
                            PaymentMethod = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 16, 23, 28, 48, 761, DateTimeKind.Utc).AddTicks(1778),
                            IsDeleted = false,
                            PaymentMethod = "Credit"
                        });
                });

            modelBuilder.Entity("gms.data.Models.Subscription.PlanEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxBranchNumber")
                        .HasColumnType("int");

                    b.Property<int>("MaxMemberNumberPerBranch")
                        .HasColumnType("int");

                    b.Property<int>("MaxStaffNumberPerBranch")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerMonth")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricePerYear")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReminderDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("gms.SystemPlan", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 16, 23, 28, 48, 763, DateTimeKind.Utc).AddTicks(6293),
                            IsDeleted = false,
                            MaxBranchNumber = 1,
                            MaxMemberNumberPerBranch = 50,
                            MaxStaffNumberPerBranch = 20,
                            PlanName = "free_trial",
                            PricePerMonth = 0m,
                            PricePerYear = 0m,
                            ReminderDays = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 16, 23, 28, 48, 763, DateTimeKind.Utc).AddTicks(6311),
                            IsDeleted = false,
                            MaxBranchNumber = 3,
                            MaxMemberNumberPerBranch = 100,
                            MaxStaffNumberPerBranch = 30,
                            PlanName = "startup",
                            PricePerMonth = 500m,
                            PricePerYear = 5000m,
                            ReminderDays = 10
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 16, 23, 28, 48, 763, DateTimeKind.Utc).AddTicks(6316),
                            IsDeleted = false,
                            MaxBranchNumber = 5,
                            MaxMemberNumberPerBranch = 200,
                            MaxStaffNumberPerBranch = 40,
                            PlanName = "business",
                            PricePerMonth = 1000m,
                            PricePerYear = 10000m,
                            ReminderDays = 10
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 3, 16, 23, 28, 48, 763, DateTimeKind.Utc).AddTicks(6321),
                            IsDeleted = false,
                            MaxBranchNumber = 10,
                            MaxMemberNumberPerBranch = 400,
                            MaxStaffNumberPerBranch = 50,
                            PlanName = "enterprise",
                            PricePerMonth = 2000m,
                            PricePerYear = 20000m,
                            ReminderDays = 10
                        });
                });

            modelBuilder.Entity("gms.data.Models.Subscription.SubscriptionPaymentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("PaymentMethodId")
                        .HasColumnType("tinyint");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId")
                        .IsUnique();

                    b.ToTable("gms.SubscriptionPayment", (string)null);
                });

            modelBuilder.Entity("gms.data.Models.Subscription.SubscriptionStatusEnumEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("BadgeColorId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("gms.SubscriptionStatusEnum", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeColorId = (byte)2,
                            CreatedAt = new DateTime(2024, 3, 16, 23, 28, 48, 761, DateTimeKind.Utc).AddTicks(7001),
                            IsDeleted = false,
                            SubscriptionStatus = "Active"
                        },
                        new
                        {
                            Id = 2,
                            BadgeColorId = (byte)4,
                            CreatedAt = new DateTime(2024, 3, 16, 23, 28, 48, 761, DateTimeKind.Utc).AddTicks(7018),
                            IsDeleted = false,
                            SubscriptionStatus = "Suspend"
                        },
                        new
                        {
                            Id = 3,
                            BadgeColorId = (byte)6,
                            CreatedAt = new DateTime(2024, 3, 16, 23, 28, 48, 761, DateTimeKind.Utc).AddTicks(7022),
                            IsDeleted = false,
                            SubscriptionStatus = "Cancelled"
                        },
                        new
                        {
                            Id = 4,
                            BadgeColorId = (byte)3,
                            CreatedAt = new DateTime(2024, 3, 16, 23, 28, 48, 761, DateTimeKind.Utc).AddTicks(7026),
                            IsDeleted = false,
                            SubscriptionStatus = "Expired"
                        });
                });

            modelBuilder.Entity("gms.data.Models.Subscription.SubscriptionTypeEnumEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("gms.SubscriptionTypeEnum", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 16, 23, 28, 48, 762, DateTimeKind.Utc).AddTicks(1571),
                            IsDeleted = false,
                            SubscriptionType = "Monthly"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 16, 23, 28, 48, 762, DateTimeKind.Utc).AddTicks(1585),
                            IsDeleted = false,
                            SubscriptionType = "Annually"
                        });
                });

            modelBuilder.Entity("gms.data.Models.Subscription.SystemSubscriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("PlanId")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("SubscriptionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SubscriptionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubscriptionStartTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("SubscriptionStatusId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SubscriptionTypeId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("gms.SystemSubscription", (string)null);
                });

            modelBuilder.Entity("gms.data.Models.Gym.GymBranchEntity", b =>
                {
                    b.HasOne("gms.data.Models.Gym.GymEntity", "Gym")
                        .WithMany("GymBranches")
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("gms.data.Models.Subscription.SubscriptionPaymentEntity", b =>
                {
                    b.HasOne("gms.data.Models.Subscription.SystemSubscriptionEntity", "Subscription")
                        .WithOne()
                        .HasForeignKey("gms.data.Models.Subscription.SubscriptionPaymentEntity", "SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("gms.data.Models.Gym.GymEntity", b =>
                {
                    b.Navigation("GymBranches");
                });
#pragma warning restore 612, 618
        }
    }
}
