// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gms.data;

#nullable disable

namespace gms.data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240302091532_UpdateSubscriptionStatusAndAddBadgeColorEnum")]
    partial class UpdateSubscriptionStatusAndAddBadgeColorEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gms.data.Models.SubscriptionStatusEnumEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("BadgeColorId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("gms.SubscriptionStatusEnum", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeColorId = (byte)2,
                            CreatedAt = new DateTime(2024, 3, 2, 9, 15, 31, 890, DateTimeKind.Utc).AddTicks(765),
                            IsDeleted = false,
                            SubscriptionStatus = "Active"
                        },
                        new
                        {
                            Id = 2,
                            BadgeColorId = (byte)4,
                            CreatedAt = new DateTime(2024, 3, 2, 9, 15, 31, 890, DateTimeKind.Utc).AddTicks(774),
                            IsDeleted = false,
                            SubscriptionStatus = "Suspend"
                        },
                        new
                        {
                            Id = 3,
                            BadgeColorId = (byte)6,
                            CreatedAt = new DateTime(2024, 3, 2, 9, 15, 31, 890, DateTimeKind.Utc).AddTicks(776),
                            IsDeleted = false,
                            SubscriptionStatus = "Cancelled"
                        },
                        new
                        {
                            Id = 4,
                            BadgeColorId = (byte)3,
                            CreatedAt = new DateTime(2024, 3, 2, 9, 15, 31, 890, DateTimeKind.Utc).AddTicks(778),
                            IsDeleted = false,
                            SubscriptionStatus = "Expired"
                        });
                });

            modelBuilder.Entity("gms.data.Models.SubscriptionTypeEnumEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("gms.SubscriptionTypeEnum", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 2, 9, 15, 31, 890, DateTimeKind.Utc).AddTicks(2640),
                            IsDeleted = false,
                            SubscriptionType = "Monthly"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 2, 9, 15, 31, 890, DateTimeKind.Utc).AddTicks(2645),
                            IsDeleted = false,
                            SubscriptionType = "Annually"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
