// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gms.entityframeworkcore.Data;

#nullable disable

namespace gms.data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240126200544_addCategoryEntity")]
    partial class addCategoryEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gms.data.Models.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("gms.category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10c0d450-fa01-451f-8a1f-ce8f9155f4c4"),
                            CreatedAt = new DateTime(2024, 1, 26, 22, 5, 44, 154, DateTimeKind.Local).AddTicks(7080),
                            IsDeleted = false,
                            Name = "Regular"
                        },
                        new
                        {
                            Id = new Guid("11c076f9-ff15-4902-87b1-18d67328cf03"),
                            CreatedAt = new DateTime(2024, 1, 26, 22, 5, 44, 154, DateTimeKind.Local).AddTicks(7146),
                            IsDeleted = false,
                            Name = "Limited"
                        },
                        new
                        {
                            Id = new Guid("a19b27b5-091b-43de-9f1d-9cdfaa1f2b17"),
                            CreatedAt = new DateTime(2024, 1, 26, 22, 5, 44, 154, DateTimeKind.Local).AddTicks(7150),
                            IsDeleted = false,
                            Name = "Total Gym Exercises for Abs (Abdomininals)"
                        },
                        new
                        {
                            Id = new Guid("04ec7783-f082-4ee1-9d85-e8bd0d65a9da"),
                            CreatedAt = new DateTime(2024, 1, 26, 22, 5, 44, 154, DateTimeKind.Local).AddTicks(7153),
                            IsDeleted = false,
                            Name = "Total Gym Exercises for Legs"
                        },
                        new
                        {
                            Id = new Guid("8a89450d-119b-436f-8f77-63dcff7c0648"),
                            CreatedAt = new DateTime(2024, 1, 26, 22, 5, 44, 154, DateTimeKind.Local).AddTicks(7180),
                            IsDeleted = false,
                            Name = "Total Gym Exercises for Biceps"
                        },
                        new
                        {
                            Id = new Guid("93bf45e9-1e72-43a8-8aee-efbf74761f16"),
                            CreatedAt = new DateTime(2024, 1, 26, 22, 5, 44, 154, DateTimeKind.Local).AddTicks(7188),
                            IsDeleted = false,
                            Name = "Exercise"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
