// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gms.entityframeworkcore.Data;

#nullable disable

namespace gms.data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240126205903_AddGymEventPlaceEntity")]
    partial class AddGymEventPlaceEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gms.data.Models.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("gms.category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ebcbe191-6fef-47c0-9fe0-34216dcd194b"),
                            CreatedAt = new DateTime(2024, 1, 26, 22, 59, 3, 518, DateTimeKind.Local).AddTicks(1135),
                            IsDeleted = false,
                            Name = "Regular"
                        },
                        new
                        {
                            Id = new Guid("2b131b6a-0f99-43be-ba1b-2f3f4e440940"),
                            CreatedAt = new DateTime(2024, 1, 26, 22, 59, 3, 518, DateTimeKind.Local).AddTicks(1222),
                            IsDeleted = false,
                            Name = "Limited"
                        },
                        new
                        {
                            Id = new Guid("dae0c103-e52d-459d-b5c9-6d02dcbf59f5"),
                            CreatedAt = new DateTime(2024, 1, 26, 22, 59, 3, 518, DateTimeKind.Local).AddTicks(1227),
                            IsDeleted = false,
                            Name = "Total Gym Exercises for Abs (Abdomininals)"
                        },
                        new
                        {
                            Id = new Guid("13c825c4-b6c2-449d-ba97-7f552e17cce7"),
                            CreatedAt = new DateTime(2024, 1, 26, 22, 59, 3, 518, DateTimeKind.Local).AddTicks(1231),
                            IsDeleted = false,
                            Name = "Total Gym Exercises for Legs"
                        },
                        new
                        {
                            Id = new Guid("12220ade-9671-444b-a15f-a92c023ecc2b"),
                            CreatedAt = new DateTime(2024, 1, 26, 22, 59, 3, 518, DateTimeKind.Local).AddTicks(1234),
                            IsDeleted = false,
                            Name = "Total Gym Exercises for Biceps"
                        },
                        new
                        {
                            Id = new Guid("a98e2629-0768-4b45-8d02-bae3a216f60b"),
                            CreatedAt = new DateTime(2024, 1, 26, 22, 59, 3, 518, DateTimeKind.Local).AddTicks(1241),
                            IsDeleted = false,
                            Name = "Exercise"
                        });
                });

            modelBuilder.Entity("gms.data.Models.GymEventPlaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Place")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("gms.gym_event_place", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
